
title: Duck Anatomy
description: >-
  Dr Armelle Bauer, R&D Software Engineer, Computer Graphics, real-time, animation, interaction, virtual humans, mixed reality, C++, Python, AI, software architecture.

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Google services
google_analytics: UA-191026714-1

# Site Author
author:
  name: "Armelle Bauer"
  email: armelle.bauer.ab@gmail.com

links:
  - label: "Email"
    icon: "fa-envelope-o"
    url: "mailto:armelle.bauer.ab@gmail.com"
  - label: "GitHub"
    icon: "fa-github"
    url: "https://github.com/duck-anatomy"
  - label: "LinkedIn"
    icon: "fa-linkedin"
    url: "https://www.linkedin.com/in/armelle-bauer"
  - label: "Twitter"
    icon: "fa-twitter"
    url: "https://twitter.com/armellebauer"