
title: Duck Anatomy
description: >-
  Dr Armelle Bauer, R&D Software Engineer, Computer Graphics, real-time, animation, interaction, mixed reality, C++, Python, AI, software architecture.

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Google services
# Analytics
analytics:
  provider: "google-universal"
  google:
    tracking_id: G-HR0BEM66DV
    anonymize_ip: true

# Site Author
author:
  name: "Armelle Bauer"
  email: armelle.bauer.ab@gmail.com

links:
  - label: "Email"
    icon: "fa-envelope-o"
    url: "mailto:armelle.bauer.ab@gmail.com"
  - label: "GitHub"
    icon: "fa-github"
    url: "https://github.com/duck-anatomy"
  - label: "LinkedIn"
    icon: "fa-linkedin"
    url: "https://www.linkedin.com/in/armelle-bauer-5030a973"